apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vinod
  template:
    metadata:
      labels:
        app: vinod
    spec:
      containers:
      - name: vinod-app
        image: vinodkhathi/vinod-img:v1
        ports:
        - containerPort: 8080